services:
#  actual-budget:
#    image: docker.io/actualbudget/actual-server:latest
#    container_name: actual-budget
#    ports:
#      - "5006:5006"
#    volumes:
#      - ./actual-data:/data:Z
#    restart: always
#    healthcheck:
#      test: (ls -l /proc/*/exe | grep -q node && echo "App running") || exit 1
#      interval: 60s
#      retries: 2
#      start_period: 20s
#      timeout: 10s

  akaku-sync:
    image: "node:lts"
    container_name: akahu-sync
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./akahu-sync:/home/node/app:Z
    command: bash -c "/home/node/app/start.sh"
    restart: always
    healthcheck:
      disable: true
